security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        customers:
             entity: { class: AppBundle:User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/checkout, roles: ROLE_USER }
